### ISSUE TITLE
Logical operation order after compilation

### ISSUE THREAD

**Issue by KTMonadjem** [PRETgroup/easy-rte#1]
When '=' is used during logical operations in the erte file, and is combined with "or's" and "and's", the compiler incorrectly assigns the order of operations.

For example:
((a = 1 or b = 3) and c = 0) 
compiles to:
(inputs.a == 1 || inputs.b == 3 and inputs.c == 0)

This does not seem to happen if '<', '>' or booleans are used in place of the '='.

**Comment by KTMonadjem** [comment]
Update on previous issue:

This line:
-> violation on ((cobject1 = 1 or cobject1 = 3) and !((speed = 1 and (slow_brake or fast_brake)) or (speed = 2 and fast_brake))) recover slow_brake := 0;

compiles to:
if(inputs->cobject1 == 1 && !inputs->speed == 1 && outputs->slow_brake || outputs->fast_brake)
if(inputs->cobject1 == 3 && !inputs->speed == 1 && outputs->slow_brake || outputs->fast_brake)
if(inputs->cobject1 == 1 && !inputs->speed == 2 && outputs->fast_brake) 
if(inputs->cobject1 == 3 && !inputs->speed == 2 && outputs->fast_brake) 

and the parenthesized "or" is executed incorrectly.

**Comment by kiwih** [comment]
I just fixed the first issue for `((a = 1 or b = 3) and c = 0)` in goFB. Can you make a smaller worked example for the second issue / check if it still doesn't work?
